language: python

python:
  - "3.5"
  - "2.7"
  - "pypy"

env:
  - "$DJANGO='django<1.9'"
  - "$DJANGO='django<1.10'"

# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -r requirements-dev.txt
  - pip install coveralls

  - nvm install 6
  - npm install

# command to run tests
script:
  - "cd backend && python manage.py test --keepdb && cd .."
  - npm test

cache:
  pip: true
  directories:
    - node_modules  # NPM pachages

before_script:
  - flake8 backend --config=backend/flake8
  - python backend/manage.py migrate

after_success: coveralls
