# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# what combinations to test
environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - nodejs_version: 6
      PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"

platform:
  - x86
  - x64

skip_branch_with_pr: true

init:
  - git config --global core.autocrlf input
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install -g nuxt-cli@0.0.1
  - cmd: npm install
  - cmd: pip install -r requirements-dev.txt

before_test:
  - cmd: flake8 backend --config=backend/flake8
  - cmd: python backend/manage.py migrate

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - "cd backend && python manage.py test --keepdb && cd .."
  - npm test
